-- The source of truth for the current database schema is the numbered
-- migration files in supabase/migrations/, applied in order (002 through
-- the highest number present). This file is not it.
--
-- schema_baseline.sql in this same directory is the pre-migration bootstrap
-- state (profiles, attempt_reports, and the earliest leaderboard views),
-- kept for historical reference only. Every table, view, and policy added
-- since then, BiOClash, BiOLab, doubts, papers contributions, page ratings,
-- and everything else, exists only in supabase/migrations/.
--
-- To stand up a fresh database: run schema_baseline.sql first, then every
-- migration in supabase/migrations/ in numeric order.
