baseURL = "https://boguide.vercel.app/"
title = "BiOGuide for Biology Olympiads"
theme = "hextra"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.katex]
    enable = true

[menu]
  [[menu.main]]
    name = "Resources"
    url = "/resources/"
    weight = 1
  [[menu.main]]
    name = "Papers"
    url = "/papers/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.main]]
    name = "Articles"
    url= = "/articles/"
    weight = 4

[params]
  # Navbar settings
  [params.navbar]
    title = "BiOGuide for Biology Olympiads"
    [params.navbar.logo]
      path = "/logo.png"
      width = 40
      height = 40
      alt = "BioGuide Logo"
  # Image zoom
  [params.imageZoom]
    enable = true
  # Footer
  [params.footer]
    copyright = "© 2026 BioGuide for IBO Vilnius"
  # Table of contents
  toc = true
  # Custom CSS (relative to static/ folder)
  custom_css = ["css/custom.css"]